version: "3"

services:
  database:
    image: postgres
    container_name: database_scheduling
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=scheduling
    volumes:
    - pgdata:/data/postgres
    network_mode: host
  app: 
   build: .
   container_name: app
   ports: -3333:3333
      # informar o volume abaixo
      # windows:
      #- C:\\caminho\\pasta:/var/lib/postgresql/data
      # linux:
      #- /var/opt/pasta:/var/lib/postgresql/data
  # app:
  #   build: .
  #   container_name: app
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   links: 
  #     - database
  #   depends_on:
  #     - database

volumes:
  pgdata:
    driver: local